# Latest version under the main version 16 (LTS).
FROM node:16-alpine

# Default working directory
WORKDIR /app

# We set the entrypoint so that the container could work similar to a command.
ENTRYPOINT [ "npm" ]
